#!/bin/bash
## ----------------------------------------------
## @File: utils

##
## @name set_color
##
## sets the color of the text. Only green is implemented
##
function set_color() {
    local color=$1
    local style=$2
    if [ "$color" == "GREEN" ]; then
        echo -ne "\e[32m"
    elif [ "$color" == "DEFAULT" ]; then
        echo -ne "\e[0m"
    fi
    if [ "$style" == "BOLD" ]; then
        echo -ne "\e[1m"
    fi
}

##
## @name clear_screen()
##
## clear all the lines of the screen
##
function clear_screen() {
    for i in $(seq 2 $ROWS)
    do
        set_position $i 0
        erase_to_end
    done
}

##
## @name update_score
##
## updates the scoreboard
##
function update_score() {
    set_position 0 0
    FORWARD $(($COLS/4))
    echo -ne "SCORE"
    set_color "GREEN" "BOLD"
    echo -ne " $SCORE"
    set_color "DEFAULT"
    FORWARD $(($COLS/4)) 
    echo -ne "HIGH"
    set_color "GREEN" "BOLD"
    echo -ne " $HIGH"
    set_color "DEFAULT"
    FORWARD $(($COLS/4))
    echo -ne "LIVES"
    set_color "GREEN" "BOLD"
    echo -ne " $LIVES"
    set_color "DEFAULT"
    set_color "GREEN" "BOLD"
}

##
## @name init_screen()
##
## initialize the screen
##
function init_screen() {
    for i in $(seq 2 $ROWS)
    do
        echo
    done
}

##
## @name debug()
##
## A logger to print debug statements
##
function debug() {
    local info=$1
    the_date=$(date +'%Y%m%d:%H%M%S')
    echo "[$the_date] $info" >> ~/temp/snake-debug
}

##
## @name showDocs
##
## prints out these comments
##
function showDocs() {
  grep -Ir '^##' . | sed -e 's/^.*##//' 1>&2
}

## END utils
